name: Monthly Reminder Email

on:
  # Trigger on the first day of each month at 09:00 UTC (GitHub Actions uses UTC)
  schedule:
    - cron: '0 9 1 * *'
  # Allow manual trigger if needed via the GitHub UI
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip

      - name: Send reminder email
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python send_reminder.py
